name: CC-Essentials-plugin
main: fr.cartooncraft.essentials.plugin.CCEssentials
version: 1.0
depend: [CC-Essentials-lib]
commands:
    list:
        description: Return players list.
        usage: /list
    spawn:
        description: Teleport you or somebody to spawn. 
        usage: /spawn [player]
    tp:
        description: Teleports you to another player, or teleport a player to another.
        usage: /tp <player> | /tp <player1> <player2> | /tp <x> <y> <z> | /tp <player> <x> <y> <z>
        aliases: [teleport]
    kill:
        description: Kill yourself or a player
        usage: /kill [player]
    broadcast:
        description: ...
        usage: /broadcast <msg>
    tell:
        description: Send a message to another guy.
        usage: /tell <player> <msg>
        aliases: [whisp, whisper, t, w, pm, mp, msg]
    kick:
        description: Kick a player with reason.
        usage: /kick <player> [reason]
    suicide:
        description: Kill yourself.
        usage: /suicide
    heal:
        description: Heal a player.
        usage: /heal [player]
    healall:
        description: Heal all players.
        usage: /healall
    feedall:
        description: Feed all players.
        usage: /feedall
    feed:
        description: Feed a player.
        usage: /feed [player]
    tpall:
        description: Teleport all players.
        usage: /tpallall | /tpall <player> | /tpall <x> <y> <z>
    kickall:
        description: Kick all players (except OPs).
        usage: /kickall <reason>
    kickallop:
        description: Kick all players (include OPs, except you).
        usage: /kickallop <reason>
    godmode:
        description: Toggle godmode for yourself or the specified player.
        usage: /godmode [player]
        aliases: [god]
    gamemode:
        description: Change the player's godmode.
        usage: /gamemode | /gamemode <0|1|2> | /gamemode <name> | /gamemode <name> <mode>
        aliases: [gm]
    isingodmode:
        description: Tell the sender if the sender or the specified player is in godmode.
        usage: /isingodmode [player]
        aliases: [isingod, isgod]
    roll:
        description: Return a random number between two given numbers. (default 1-100)
        usage: /roll | /roll <x-y> | /roll <x> <y>
        aliases: [random, rand]
    reply:
        description: Reply to the latest message
        usage: /reply <message>
        aliases: [r]
    life:
        description: Returns or modify the player's HP.
        usage: /life <player> [get|set|add|remove] [amount]
        aliases: [hp, health]
    xp:
        description: Returns or set the player's experience.
        usage: /xp [player] [get|set|add|remove] amount<L>
    head:
        description: Give you a player's head.
        usage: /head <player>
    top:
        description: Teleport yourself to the highest block.
        usage: /top
